# Generated by Django 4.1.1 on 2022-09-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='discounted price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='qty'),
        ),
    ]
